### ISSUE TITLE
understanding the code

### ISSUE THREAD

**Issue by Minger** [Mattie/cataclysm#10]
Great work! I'm trying to understand how the magic happens.

Where is `petition_completion2` defined?
https://github.com/Mattie/cataclysm/blob/226bbe34cd0e3d2bbe25913df33a90b4239a3a18/cataclysm/doomed.py#L152

and where does the call to openai take place? I could not find a usage of the openai client in the code.

Thanks!

**Comment by Mattie** [comment]
Thanks so much for your interest and sorry it wasn't clear there.

I'm using a wrapper library [plunkylib](/Mattie/plunkylib) (though I'll be changing that to my upcoming simpler [chatsnack](/Mattie/chatsnack) library).

The gist of these libraries is that you describe the prompt and parameters in yaml rather than hardcode them all the time. Handy for tweaking/swapping out prompts and params.

This folder contains the prompt and parameter yaml definitions given to plunkylib: 
 https://github.com/Mattie/cataclysm/tree/master/datafiles/plunkylib

(Chatsnack will work similarly, just it'll be a single yaml file rather than 3 separate ones )

**Comment by Minger** [comment]
Thanks, my IDE was not pointing to the correct python interpreter thus not showing the reference to the plunkylib code. I see that package repo now.
